export const Houses_data = [
    {
        id: 1,
        Image: "https://i.pinimg.com/550x/fc/07/40/fc0740d7c26d93974e117cb88a81bc36.jpg",
        price: 2700,
        houseName: "Palm Harbour",
        hAddress: "769 Hilpert Tunnel Apt. 568",
        houseAddress: "hk",
        bed: 4,
        preference: 'girl',
        bathroom: 2,
        area: `5 x 6`
    },
    {
        id: 2,
        Image: "https://images.unsplash.com/photo-1625602812206-5ec545ca1231?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YW1lcmljYW4lMjBob3VzZXxlbnwwfHwwfHw%3D&w=1000&q=80",
        price: 2000,
        houseName: "Beverly Springfield",
        hAddress: "Lengyel sétaút 42",
        houseAddress: "india",
        bed: 6,
        preference: 'girl',
        bathroom: 4,
        area: `12 x 6`
    },
    {
        id: 3,
        Image: "https://www.bhg.com/thmb/ql_GC8PEm0yvPJYqh_3nsGS_dx8=/1799x1280/filters:fill(auto,1)/white-modern-house-curved-patio-archway-c0a4a3b3-aa51b24d14d0464ea15d36e05aa85ac9.jpg",
        price: 3500,
        houseName: "faulkner Ave",
        hAddress: "160 Mraz Loaf",
        houseAddress: "india",
        bed: 5,
        bathroom: 4,
        area: `5x1`
    },
    {
        id: 4,
        Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3lfcg7WiPD6tDKMA_HAiuWZfxCHJOIy8PVJ50_cE7KCWhX2gS9fpL-c94o7MpdklbiVE&usqp=CAU",
        price: 2700,
        houseName: "1/3, Sterling Apt",
        hAddress: "2390 Erich Manor",
        houseAddress: "india",
        bed: 4,
        preference: 'girl',
        bathroom: 2,
        area: `5x6`
    },
    {
        id: 5,
        Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_d4xf8g7hrAOpthHSSJ9zM_Zf9Rh6Swj5pw&usqp=CAU",
        price: 2700,
        houseName: "Bohra Colony",
        hAddress: "6961 Doyle Views",
        houseAddress: "hk",
        preference: 'boy',
        bed: 4,
        bathroom: 2,
        area: `5x6`
    },
    {
        id: 6,
        Image: "https://m1.cbhomes.com/p/805/54903672/9A9276b1fcb6492/s23cc.jpg",
        price: 2700,
        houseName: "Hsidc Indl Estate",
        hAddress: "125 Goodwin Estates",
        houseAddress: "india",
        bed: 4,
        preference: 'boy',
        bathroom: 2,
        area: `5x6`
    },
    {
        id: 7,
        Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrAxHz-rFOKn_kkKk9em21bg9uxao6fOkM5A&usqp=CAU",
        price: 4000,
        houseName: "30 New  House",
        hAddress: "7, Jalan 27Y",
        houseAddress: "india",
        preference: 'family',
        bed: 1,
        bathroom: 1,
        area: `1x2`
    },
    {
        id: 8,
        Image: "https://rentpath-res.cloudinary.com/$img_current/t_3x2_jpg_md/t_unpaid/ef412d70e4e4b49ed92e10541a02c4b9",
        price: 4400,
        houseName: "Maker Chamber 4, 111",
        hAddress: "60, Lorong 4/1E",
        houseAddress: "japan",
        bed: 6,
        bathroom: 3,
        area: `2x5`
    }, {
        id: 9,
        Image: "https://images.zerodown.com//photos/ntreis/421022728/421022728_1.jpg?tr=f-auto,w-360,h-270",
        price: 2700,
        houseName: "Malleswaram Lane",
        hAddress: "Grevegade 4H, st. tv",
        houseAddress: "taiwan",
        preference: 'family',
        bed: 6,
        bathroom: 4,
        area: `8x6`
    }, {
        id: 10,
        Image: "https://photosrp.dotproperty.co.th/1.0-DP-52561-PP-9224595-53271012362ce26e5f410f-1-540-360/4-bedroom-house-for-rent-in-burasiri-san-phi-suea-chiang-mai-pa-daet-chiang-mai",
        price: 2300,
        houseName: "nrshantitheatrblr-4",
        hAddress: "Skovvej 63, 3. sal.",
        houseAddress: "russia",
        preference: 'family',
        bed: 3,
        bathroom: 1,
        area: `4x3`
    }, {
        id: 11,
        Image: "https://pi.movoto.com/p/846/269351_0_qbAzVf_p.jpeg",
        price: 5500,
        houseName: "Jewel Crown",
        hAddress: "Passeig Rodrigo",
        houseAddress: "germany",
        preference: 'family',
        bed: 7,
        bathroom: 4,
        area: `8x6`
    },
    {
        id: 12,
        Image: "http://www.calicutproperties.com/en/upload/4376131607080828.jpg",
        price: 1659,
        houseName: "71, Bhajipala Lane",
        hAddress: "Off. Nagdevi houseName",
        houseAddress: "india",
        preference: 'family',
        bed: 3,
        bathroom: 1,
        area: `2x3`,
    },

    {
        id: 13,
        Image: "https://www.residence-brehova.com/images/one-bedroom/detail/large/bedroom_1.jpg",
        price: 1659,
        houseName: "65/3 mischef",
        hAddress: "dart push 1/2",
        houseAddress: "india",
        preference: 'family',
        bed: 1,
        bathroom: 1,
        area: `1x1`,
    },
    {
        id: 14,
        Image: "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGJlZHJvb218ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
        price: 1245,
        houseName: "luisung 21",
        hAddress: "Delta square",
        houseAddress: "india",
        preference: 'family',
        bed: 1,
        bathroom: 1,
        area: `2x2`,
    },
    {
        id: 15,
        Image: "https://images.unsplash.com/photo-1635428335190-95f20a76cb47?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NjJ8fGJlZHJvb218ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
        price: 6066,
        houseName: "Alexame Avenue",
        hAddress: "Namblar Street",
        houseAddress: "russia",
        preference: 'family',
        bed: 1,
        bathroom: 2,
        area: `2x1`,
    },
    {
        id: 16,
        Image: "https://plus.unsplash.com/premium_photo-1661895255081-cfdb2bf642da?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Njd8fGJlZHJvb218ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
        price: 7000,
        houseName: "Chialong Chemo",
        hAddress: "Chilanao Street",
        preference: 'family',
        houseAddress: "japan",
        bed: 1,
        bathroom: 2,
        area: `2x3`,
    },
    {
        id: 17,
        Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8QrA800Og-SzMpz5I4jIUdxyfOzBOT9S-6g&usqp=CAU",
        price: 2563,
        houseName: "Nomad House",
        hAddress: "Metroroute Colony",
        houseAddress: "taiwan",
        preference: 'family',
        bed: 2,
        bathroom: 1,
        area: `3x2`,
    },
    {
        id: 18,
        Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv5FLNUqWYRzu7UJLjt1CrGYl39z8J2nd5BQ&usqp=CAU",
        price: 2863,
        houseName: "NomanClature",
        hAddress: "Retire Street",
        houseAddress: "india",
        preference: 'family',
        bed: 2,
        bathroom: 2,
        area: `3x2`,
    },
];

//location(string) -india,hk and etc
export const getHouesByLocation = (location) => {
    return Houses_data.filter(house => house.houseAddress === location);
}